### PR TITLE
Bump axios to ^0.21.1

### PR DESCRIPTION
**Pull request by rwillians**

### CODE REVIEW

**Comment by Gerhut** [comment]
Could you please describe your fix about the "Compile Error"?

**Comment by rwillians** [comment]
@Gerhut sure

https://github.com/Gerhut/axiosist/pull/40/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R3

The type you are importing inside the annotation is `Server` interface (which the compiler is importing from `@types/node`, not `http`) and it conflicts with the `Server` class imported from `http`. It would've been fine if the code was ts but when generating typings from js annotations, referring to imported types and concrete code mustn't conflict otherwise the compiler will raise "ambiguity" error.


https://github.com/Gerhut/axiosist/pull/40/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R56

As for the callback, `listen/3`'s signature expects a function which takes no arguments but `resolve`'s signature takes one argument, therefore `resolve` can't be passed as an argument directly. I called `resolve(undefined)` instead of `resolve(null)` bc I wanted an explicit indicator that I'm not resolving any actual value, I'm just fufilling the function's signature.

These errors weren't showing on travis, but they showed up when compiling on node 15.5.1

**Comment by rwillians** [comment]
@Gerhut just out of curiosity, was there a reason for you not to commit package-lock.json?

**Comment by Gerhut** [comment]
> @Gerhut sure
> 
> https://github.com/Gerhut/axiosist/pull/40/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R3
> 
> The type you are importing inside the annotation is `Server` interface (which the compiler is importing from `@types/node`, not `http`) and it conflicts with the `Server` class imported from `http`. It would've been fine if the code was ts but when generating typings from js annotations, referring to imported types and concrete code mustn't conflict otherwise the compiler will raise "ambiguity" error.
> 
> https://github.com/Gerhut/axiosist/pull/40/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R56
> 
> As for the callback, `listen/3`'s signature expects a function which takes no arguments but `resolve`'s signature takes one argument, therefore `resolve` can't be passed as an argument directly. I called `resolve(undefined)` instead of `resolve(null)` bc I wanted an explicit indicator that I'm not resolving any actual value, I'm just fufilling the function's signature.
> 
> These errors weren't showing on travis, but they showed up when compiling on node 15.5.1

It seems these compile failures are not caused by upgrading axios, will look into and fix them separately.

**Comment by Gerhut** [comment]
> @Gerhut just out of curiosity, was there a reason for you not to commit package-lock.json?

`package-lock` is not used in installed as a dependency, remove it and try to simulate the same scenario in CI.

**Comment by Gerhut** [comment]
Seems these 2 compile error are introduced in the following breaking changes in TypeScript 4.1:

- https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#unmatched-parameters-are-no-longer-related
- https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#resolves-parameters-are-no-longer-optional-in-promises

I will manually upgrade TypeScript to 4.1 and fix these errors accordingly

**Comment by Gerhut** [comment]
I've upgraded the TypeScript to 4.1 and fix all compile errors, including another incorrect `socket hang up` test case, will publish a new major version.

Let's back to the topic, I think axios 0.21.1 is included in the current version range(^0.20.0) so the library users could upgrade by themselves (maybe `npm audit fix`). Are you facing any upgrading issue? If so, could you please show your case to me and let's figure out the root cause.

**Comment by rwillians** [comment]
Ohhh I see what's wrong, the published axiosist v0.9.0 is actually requiring axios ^0.19.1
https://github.com/rwillians/fykit/blob/master/packages/appify/package-lock.json#L432
Maybe you've updated axios' version range here but forgot to publish?

**Comment by Gerhut** [comment]
Just published v0.10.0 with es module typings. If you need a version like v0.9.1 which contains only axios upgrading please let me know.

**Comment by rwillians** [comment]
> Just published v0.10.0 with es module typings. If you need a version like v0.9.1 which contains only axios upgrading please let me know.

Thanks, 0.10.0 works for me

**Pull request closed without merging**
